package param;

public interface GlobalPara {
	int ZEROCOIN_DEFAULT_SECURITYLEVEL = 80;
	int ZEROCOIN_MIN_SECURITY_LEVEL = 80;
	int ZEROCOIN_MAX_SECURITY_LEVEL = 80;
	int ACCPROOF_KPRIME = 160;
	int ACCPROOF_KDPRIME = 128;
	int MAX_COINMINT_ATTEMPTS = 10000;
	int ZEROCOIN_MINT_PRIME_PARAM = 20;
	String ZEROCOIN_VERSION_STRING = "0.11";
	int ZEROCOIN_VERSION_INT	 = 11;
	String ZEROCOIN_PROTOCOL_VERSION = "1";
	int HASH_OUTPUT_BITS = 256;
	String ZEROCOIN_COMMITMENT_EQUALITY_PROOF = "COMMITMENT_EQUALITY_PROOF";
	String ZEROCOIN_ACCUMULATOR_PROOF = "ACCUMULATOR_PROOF";
	String ZEROCOIN_SERIALNUMBER_PROOF = "SERIALNUMBER_PROOF";
	
}
